ERROR 2025-01-21 13:26:51,510 log Internal Server Error: /remove_service_yearly/
ERROR 2025-01-21 13:26:51,514 basehttp "POST /remove_service_yearly/ HTTP/1.1" 500 51
ERROR 2025-01-21 13:26:51,514 basehttp "POST /remove_service_yearly/ HTTP/1.1" 500 51
ERROR 2025-01-21 13:32:14,281 email_llama3 Translation API error: HTTPSConnectionPool(host='dhruva-api.bhashini.gov.in', port=443): Read timed out. (read timeout=10)
ERROR 2025-01-21 14:50:40,319 log Internal Server Error: /check_session_status/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.DatabaseError: could not receive data from server: Operation timed out
SSL SYSCALL error: Operation timed out


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DatabaseError: could not receive data from server: Operation timed out
SSL SYSCALL error: Operation timed out

ERROR 2025-01-21 14:50:40,320 basehttp "POST /check_session_status/ HTTP/1.1" 500 190252
ERROR 2025-01-21 14:50:40,320 basehttp "POST /check_session_status/ HTTP/1.1" 500 190252
ERROR 2025-01-21 15:16:38,621 views Internal server error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2025-01-21 15:16:38,623 log Internal Server Error: /signin/
ERROR 2025-01-21 15:16:38,624 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-21 15:16:38,624 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-21 15:16:40,379 views Internal server error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2025-01-21 15:16:40,380 log Internal Server Error: /signin/
ERROR 2025-01-21 15:16:40,381 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-21 15:16:40,381 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-21 15:17:19,171 views Internal server error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2025-01-21 15:17:19,175 log Internal Server Error: /signin/
ERROR 2025-01-21 15:17:19,175 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-21 15:17:19,175 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-21 18:29:43,140 email_llama3 Translation API error: HTTPSConnectionPool(host='dhruva-api.bhashini.gov.in', port=443): Read timed out. (read timeout=10)
ERROR 2025-01-21 18:29:43,245 email_llama3 Translation API error: HTTPSConnectionPool(host='dhruva-api.bhashini.gov.in', port=443): Read timed out. (read timeout=10)
ERROR 2025-01-22 15:38:51,268 views Internal server error: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

ERROR 2025-01-22 15:38:51,270 log Internal Server Error: /signin/
ERROR 2025-01-22 15:38:51,270 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:38:51,270 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:38:55,474 views Internal server error: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

ERROR 2025-01-22 15:38:55,475 log Internal Server Error: /signin/
ERROR 2025-01-22 15:38:55,476 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:38:55,476 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:47:02,064 views Internal server error: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

ERROR 2025-01-22 15:47:02,067 log Internal Server Error: /signin/
ERROR 2025-01-22 15:47:02,067 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:47:02,067 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:47:26,457 views Internal server error: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

ERROR 2025-01-22 15:47:26,460 log Internal Server Error: /signin/
ERROR 2025-01-22 15:47:26,460 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:47:26,460 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 15:49:17,559 log Internal Server Error: /guest_send_otp/
ERROR 2025-01-22 15:49:17,560 basehttp "POST /guest_send_otp/ HTTP/1.1" 500 205
ERROR 2025-01-22 15:49:17,560 basehttp "POST /guest_send_otp/ HTTP/1.1" 500 205
ERROR 2025-01-22 16:01:46,296 views Internal server error: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^

ERROR 2025-01-22 16:01:46,299 log Internal Server Error: /signin/
ERROR 2025-01-22 16:01:46,299 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 16:01:46,299 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-22 16:08:03,958 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 16:08:03,960 log Internal Server Error: /add_user/
ERROR 2025-01-22 16:08:03,960 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 16:08:03,960 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 16:13:31,851 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 16:13:31,853 log Internal Server Error: /add_user/
ERROR 2025-01-22 16:13:31,853 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 16:13:31,853 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:10:29,105 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 17:10:29,110 log Internal Server Error: /add_user/
ERROR 2025-01-22 17:10:29,110 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:10:29,110 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:11:24,847 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 17:11:24,849 log Internal Server Error: /add_user/
ERROR 2025-01-22 17:11:24,849 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:11:24,849 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:41:21,630 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 17:41:21,636 log Internal Server Error: /add_user/
ERROR 2025-01-22 17:41:21,636 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:41:21,636 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:42:42,215 views Unexpected error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2025-01-22 17:42:42,220 log Internal Server Error: /add_user/
ERROR 2025-01-22 17:42:42,220 basehttp "POST /add_user/ HTTP/1.1" 500 136
ERROR 2025-01-22 17:42:42,220 basehttp "POST /add_user/ HTTP/1.1" 500 136
ERROR 2025-01-22 17:43:11,711 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 17:43:11,714 log Internal Server Error: /add_user/
ERROR 2025-01-22 17:43:11,715 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:43:11,715 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 17:44:47,643 views Exception occurred: get() returned more than one User -- it returned 2!
ERROR 2025-01-22 17:44:47,644 log Internal Server Error: /verify_payment_yearly/
ERROR 2025-01-22 17:44:47,644 basehttp "POST /verify_payment_yearly/ HTTP/1.1" 500 64
ERROR 2025-01-22 17:44:47,644 basehttp "POST /verify_payment_yearly/ HTTP/1.1" 500 64
ERROR 2025-01-22 18:04:34,786 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 18:04:34,787 log Internal Server Error: /add_user/
ERROR 2025-01-22 18:04:34,788 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 18:04:34,788 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 18:04:45,342 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 18:04:45,343 log Internal Server Error: /add_user/
ERROR 2025-01-22 18:04:45,344 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 18:04:45,344 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 22:29:31,471 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 22:29:31,473 log Internal Server Error: /add_user/
ERROR 2025-01-22 22:29:31,473 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 22:29:31,473 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:01:51,072 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 23:01:51,079 log Internal Server Error: /add_user/
ERROR 2025-01-22 23:01:51,079 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:01:51,079 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:52:39,807 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 23:52:39,809 log Internal Server Error: /add_user/
ERROR 2025-01-22 23:52:39,809 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:52:39,809 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:53:26,165 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 23:53:26,174 log Internal Server Error: /add_user/
ERROR 2025-01-22 23:53:26,174 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:53:26,174 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:54:22,735 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 23:54:22,737 log Internal Server Error: /add_user/
ERROR 2025-01-22 23:54:22,738 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:54:22,738 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:54:35,835 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-22 23:54:35,839 log Internal Server Error: /add_user/
ERROR 2025-01-22 23:54:35,840 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-22 23:54:35,840 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 10:11:02,937 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-23 10:11:02,940 log Internal Server Error: /add_user/
ERROR 2025-01-23 10:11:02,940 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 10:11:02,940 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 10:15:53,726 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-23 10:15:53,728 log Internal Server Error: /add_user/
ERROR 2025-01-23 10:15:53,728 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 10:15:53,728 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 12:24:15,793 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:24:15,797 log Internal Server Error: /signin/
ERROR 2025-01-23 12:24:15,797 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:24:15,797 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:24:17,888 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:24:17,889 log Internal Server Error: /signin/
ERROR 2025-01-23 12:24:17,889 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:24:17,889 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:26:28,828 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:26:28,829 log Internal Server Error: /signin/
ERROR 2025-01-23 12:26:28,829 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:26:28,829 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:53,525 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:27:53,529 log Internal Server Error: /signin/
ERROR 2025-01-23 12:27:53,529 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:53,529 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:55,273 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:27:55,275 log Internal Server Error: /signin/
ERROR 2025-01-23 12:27:55,276 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:55,276 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:55,812 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:27:55,814 log Internal Server Error: /signin/
ERROR 2025-01-23 12:27:55,814 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:55,814 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:56,254 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:27:56,255 log Internal Server Error: /signin/
ERROR 2025-01-23 12:27:56,256 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:27:56,256 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:28:07,941 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 12:28:07,942 log Internal Server Error: /signin/
ERROR 2025-01-23 12:28:07,942 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 12:28:07,942 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 13:41:38,177 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 13:41:38,180 log Internal Server Error: /signin/
ERROR 2025-01-23 13:41:38,180 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 13:41:38,180 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 13:41:48,417 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 13:41:48,421 log Internal Server Error: /signin/
ERROR 2025-01-23 13:41:48,422 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 13:41:48,422 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 13:42:51,338 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 13:42:51,340 log Internal Server Error: /signin/
ERROR 2025-01-23 13:42:51,341 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 13:42:51,341 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 14:39:38,459 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-23 14:39:38,461 log Internal Server Error: /signin/
ERROR 2025-01-23 14:39:38,461 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 14:39:38,461 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-23 16:57:01,999 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-23 16:57:02,001 log Internal Server Error: /add_user/
ERROR 2025-01-23 16:57:02,001 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 16:57:02,001 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 16:57:13,467 views Unexpected error: User() got unexpected keyword arguments: 'state'
ERROR 2025-01-23 16:57:13,470 log Internal Server Error: /add_user/
ERROR 2025-01-23 16:57:13,471 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 16:57:13,471 basehttp "POST /add_user/ HTTP/1.1" 500 61
ERROR 2025-01-23 17:54:09,267 views An unexpected error occurred: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2025-01-23 17:54:09,277 log Internal Server Error: /send_email_verification_otp/
ERROR 2025-01-23 17:54:09,277 basehttp "POST /send_email_verification_otp/ HTTP/1.1" 500 136
ERROR 2025-01-23 17:54:09,277 basehttp "POST /send_email_verification_otp/ HTTP/1.1" 500 136
ERROR 2025-01-24 10:16:01,578 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-24 10:16:01,579 log Internal Server Error: /signin/
ERROR 2025-01-24 10:16:01,580 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:16:01,580 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:33,355 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-24 10:17:33,357 log Internal Server Error: /signin/
ERROR 2025-01-24 10:17:33,357 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:33,357 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:36,323 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-24 10:17:36,323 log Internal Server Error: /signin/
ERROR 2025-01-24 10:17:36,323 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:36,323 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:49,829 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-24 10:17:49,830 log Internal Server Error: /signin/
ERROR 2025-01-24 10:17:49,830 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:49,830 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:59,936 views Internal server error: 'NoneType' object has no attribute 'lower'
ERROR 2025-01-24 10:17:59,937 log Internal Server Error: /signin/
ERROR 2025-01-24 10:17:59,937 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2025-01-24 10:17:59,937 basehttp "POST /signin/ HTTP/1.1" 500 34
